name: liMil ReBuild and Release

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Get release version
        id: get_version
        run: echo "RELEASE_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Check release version
        run: echo "Release version is $RELEASE_VERSION"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install --production

      - name: ReBuild project
        run: |
            npm run build
            mkdir -p unobfuscated
            cp -f dist/worker.minify.js unobfuscated/worker.Minify.${{ env.RELEASE_VERSION }}.js
            cp -f dist/worker.rebuild.js unobfuscated/worker.ReBuild.${{ env.RELEASE_VERSION }}.js

      - name: Commit and push built worker
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f unobfuscated/worker.Minify.${{ env.RELEASE_VERSION }}.js
          git add -f unobfuscated/worker.ReBuild.${{ env.RELEASE_VERSION }}.js
          git commit -m "liMil ReBuild: Full & Minify"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Save to Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./unobfuscated
          publish_branch: bpb
          keep_files: true
